MEDIAN_COMMIT_SIZE_METRIC_KEY = "median_commit_size"
MEDIAN_COMMIT_SIZE_METRIC_NAME = "Median Commit Size"
MEDIAN_COMMIT_SIZE_CATEGORY_NAME = "General"
MEDIAN_COMMIT_SIZE_SUBCATEGORY_NAME = "Median Commit Size"