TOTAL_LINES_OF_CODE_FILTERED_METRIC_KEY = "total_lines_of_code_filtered"
TOTAL_LINES_OF_CODE_FILTERED_METRIC_NAME = "Total Lines of Code (filtered)"
TOTAL_LINES_OF_CODE_FILTERED_CATEGORY_NAME = "General"
TOTAL_LINES_OF_CODE_FILTERED_SUBCATEGORY_NAME = "Total Lines of Code (filtered)"

DEFAULT_BRANCH_NAME = "default_branch_name"
COUNTED_FILES = "counted_files"
SKIPPED_FILES = "skipped_files"

SUPPORTED_CODE_FILE_EXTENSIONS = {
    # Most common programming languages
    ".py",
    ".pyw",

    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".ts",
    ".tsx",

    ".c",
    ".h",
    ".cpp",
    ".cc",
    ".cxx",
    ".hpp",
    ".hh",
    ".hxx",
    ".cs",
    ".java",

    ".kt",
    ".kts",
    ".scala",
    ".groovy",
    ".go",
    ".rs",
    ".php",
    ".phtml",
    ".rb",
    ".pl",
    ".pm",
    ".swift",
    ".m",
    ".mm",
    ".dart",
    ".lua",
    ".r",

    # Scripting
    ".sh",
    ".bash",
    ".zsh",
    ".bat",
    ".cmd",
    ".ps1",
    ".psm1",
    ".psd1",
    ".ps1xml",

    # Web/frontend
    ".html",
    ".htm",
    ".css",
    ".scss",
    ".sass",
    ".less",
    ".vue",
    ".svelte",

    # Databases
    ".sql",
    ".psql",
    ".pgsql",
    ".mysql",
    ".ddl",
    ".dml",
    ".prisma",
    ".dbml",
    ".sql.j2",
    ".hql",
    ".cql",

    # Less popular programming languages
    ".fs",
    ".fsi",
    ".fsx",
    ".vb",
    ".jl",
    ".nim",
    ".zig",
    ".ex",
    ".exs",
    ".erl",
    ".es",
    ".escript",
    ".hrl",
    ".xrl",
    ".yrl",
    ".clj",
    ".boot",
    ".cl2",
    ".cljc",
    ".cljs",
    ".cljs.hl",
    ".cljscm",
    ".cljx",
    ".hic",
    ".elm",
    ".ml",
    ".mli",
    ".hs",
    ".lhs",
    ".lisp",
    ".cl",
    ".asd",
    ".cmake",
}

SUPPORTED_CODE_FILE_NAMES = {
    "dockerfile",
    "makefile",
    "cmakelists.txt",
    "rakefile",
    "gemfile",
    "gradlew.bat",
    "mvnw.cmd",
}

EXCLUDED_PATH_PARTS = {
    "node_modules/",
    "dist/",
    "build/",
    "coverage/",
    ".next/",
    ".nuxt/",
    ".output/",
    "out/",
    "bin/",
    "obj/",
    "vendor/",
    "target/",
    ".git/",
    ".idea/",
    ".vscode/",
    "__pycache__/",
    ".pytest_cache/",
    ".mypy_cache/",
}

EXCLUDED_FILE_EXTENSIONS = {
    ".md",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".xml",
    ".csv",
    ".tsv",
    ".log",
    ".lock",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".env",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".webp",
    ".svg",
    ".ico",
    ".pdf",
    ".mp3",
    ".wav",
    ".mp4",
    ".mov",
    ".avi",
    ".webm",
    ".zip",
    ".tar",
    ".gz",
    ".rar",
    ".7z",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".map",
    ".min.js",
    ".min.css",
}

EXCLUDED_FILE_NAMES = {
    "readme",
    "license",
    "licence",
    "copying",
    "changelog",
    "authors",
    "contributors",
    "dockerfile",
    "makefile",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".dockerignore",
    ".env",
    ".env.example",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "composer.lock",
    "cargo.lock",
}
