FIRST_COMMIT_DATE_METRIC_KEY = "first_commit_date"
FIRST_COMMIT_DATE_DISPLAY_NAME = "First Commit Date"
FIRST_COMMIT_DATE_CATEGORY_NAME = "General"
FIRST_COMMIT_DATE_SUBCATEGORY_NAME = "First Commit Date"