ESTIMATED_README_QUALITY_METRIC_KEY = "estimated_readme_quality"
ESTIMATED_README_QUALITY_METRIC_NAME = "Estimated README Quality"
ESTIMATED_README_QUALITY_CATEGORY_NAME = "Documentation"
ESTIMATED_README_QUALITY_SUBCATEGORY_NAME = "Estimated README Quality"

README_CONTENT = "readme_content"
README_HEAD_SIZE = 4000
README_TAIL_SIZE = 2000