ESTIMATED_README_QUALITY_METRIC_KEY = "estimated_readme_quality"
ESTIMATED_README_QUALITY_METRIC_NAME = "Estimated README Quality"
ESTIMATED_README_QUALITY_CATEGORY_NAME = "Documentation"
ESTIMATED_README_QUALITY_SUBCATEGORY_NAME = "Estimated README Quality"

NUM_CTX = 4096

README_CONTENT = "readme_content"