GITHUB_WIKI_TOTAL_COMMITS_METRIC_KEY = "github_wiki_total_commits"
GITHUB_WIKI_TOTAL_COMMITS_DISPLAY_NAME = "GitHub Wiki Total Commits"
GITHUB_WIKI_TOTAL_COMMITS_CATEGORY_NAME = "Documentation"
GITHUB_WIKI_TOTAL_COMMITS_SUBCATEGORY_NAME = "GitHub Wiki Total Commits"