AVERAGE_COMMITS_PER_MONTH_METRIC_KEY = "average_commits_per_month"
AVERAGE_COMMITS_PER_MONTH_METRIC_NAME = "Average Commits Per Month"
AVERAGE_COMMITS_PER_MONTH_CATEGORY_NAME = "General"
AVERAGE_COMMITS_PER_MONTH_SUBCATEGORY_NAME = "Average Commits Per Month"