MEDIAN_COMMIT_SIZE_FILTERED_METRIC_KEY = "median_commit_size_filtered"
MEDIAN_COMMIT_SIZE_FILTERED_METRIC_NAME = "Median Commit Size (filtered)"
MEDIAN_COMMIT_SIZE_FILTERED_CATEGORY_NAME = "General"
MEDIAN_COMMIT_SIZE_FILTERED_SUBCATEGORY_NAME = "Median Commit Size (filtered)"