PULL_REQUEST_ACCEPTANCE_RATE_METRIC_KEY = "pull_request_acceptance_rate"
PULL_REQUEST_ACCEPTANCE_RATE_DISPLAY_NAME = "Pull Request Acceptance Rate"
PULL_REQUEST_ACCEPTANCE_RATE_CATEGORY_NAME = "Collaboration"
PULL_REQUEST_ACCEPTANCE_RATE_SUBCATEGORY_NAME = "Pull Request Acceptance Rate"