PULL_REQUEST_ACCEPTANCE_RATE_METRIC_KEY = "pull_request_acceptance_rate"
PULL_REQUEST_ACCEPTANCE_RATE_METRIC_NAME = "Pull Request Acceptance Rate"
PULL_REQUEST_ACCEPTANCE_RATE_CATEGORY_NAME = "Collaboration"
PULL_REQUEST_ACCEPTANCE_RATE_SUBCATEGORY_NAME = "Pull Request Acceptance Rate"
MERGED_PULL_REQUESTS = "merged_pull_requests"
CLOSED_UNMERGED_PULL_REQUESTS = "closed_unmerged_pull_requests"
RESOLVED_PULL_REQUESTS = "resolved_pull_requests"