ESTIMATED_GITHUB_WIKI_QUALITY_METRIC_KEY = "estimated_github_wiki_quality"
ESTIMATED_GITHUB_WIKI_QUALITY_METRIC_NAME = "Estimated GitHub Wiki Quality"
ESTIMATED_GITHUB_WIKI_QUALITY_CATEGORY_NAME = "Documentation"
ESTIMATED_GITHUB_WIKI_QUALITY_SUBCATEGORY_NAME = "Estimated GitHub Wiki Quality"

NUM_CTX = 4096