AVERAGE_COMMIT_SIZE_FILTERED_METRIC_KEY = "average_commit_size_filtered"
AVERAGE_COMMIT_SIZE_FILTERED_METRIC_NAME = "Average Commit Size (filtered)"
AVERAGE_COMMIT_SIZE_FILTERED_CATEGORY_NAME = "General"
AVERAGE_COMMIT_SIZE_FILTERED_SUBCATEGORY_NAME = "Average Commit Size (filtered)"