LANGUAGES_USED_FILTERED_METRIC_KEY = "languages_used_filtered"
LANGUAGES_USED_FILTERED_METRIC_NAME = "Languages Used (filtered)"
LANGUAGES_USED_FILTERED_CATEGORY_NAME = "General"
LANGUAGES_USED_FILTERED_SUBCATEGORY_NAME = "Languages Used (filtered)"

LANGUAGES_USED_FILTERED_PROGRAMMING_LANGUAGES = {
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    "Dart",
    "Lua",
    "Perl",
    "Haskell",
    "Elixir",
    "Erlang",
    "Clojure",
    "F#",
    "OCaml",
    "Objective-C",
    "Visual Basic .NET",
    "Assembly",
    "Fortran",
    "COBOL",
    "Groovy",
    "Julia",
    "Nim",
    "Crystal",
    "Zig",
    "Solidity",
    "VHDL",
    "Verilog",
    "Ada",
    "Prolog",
    "Scheme",
    "Common Lisp",
    "Racket",
    "Smalltalk",
    "ABAP",
    "Apex",
    "SAS",
    "Hack",
    "Delphi",
    "Pascal",
    "Elm",
    "PureScript",
    "Reason",
    "Standard ML",
    "LabVIEW",
    "Awk",
    "Tcl",
    "Ballerina",
    "D",
    "CoffeeScript",
    "ActionScript",
    "ColdFusion",
    "PLSQL",
    "OpenCL",
    "CUDA",
    "Q#",
    "WebAssembly",
    "Chapel",
    "Io",
    "Janus",
    "Jupyter Notebook",
    "Processing",
    "RobotFramework",
    "Svelte",
    "Vue",
    "Vala",
    "XQuery",
    "Xtend",
    "Yacc",
    "ANTLR",
    "GDScript",
    "Monkey C",
    "AutoHotkey",
    "AutoIt",
    "BlitzBasic",
    "Ring",
    "Red",
    "Seed7",
    "Harbour",
    "Pony",
    "Idris",
    "Agda",
    "Mercury",
    "Forth",
    "Factor",
    "Boo",
    "Genie",
    "Rebol",
    "Inform 7",
    "Max",
    "Wolfram",
}